### ISSUE TITLE
如何切换语言

### ISSUE THREAD

**Issue by sanbei011** [goldeye0351/notion-blog#1]

**Comment by goldeye0351** [comment]
右上角有个 文/A 样子的图标,点一下就可以切换. 
内容放在了public/lang.js里面. export const lang = {
  zh: {
    BLOG: {
      CATEGORY: '类别',
      TAGS: '标签'
    },
  },
  en: {
    BLOG: {
      CATEGORY: 'Category',
      TAGS: 'Tags'
    },
  },
  ja: {},
  es: {}
}
